
CREATE DATABASE SALES_DATA;

USE SALES_DATA;

-- ADD PRIMARY KEY TO TABLES

ALTER TABLE order_details ADD PRIMARY KEY (ORDERID);

ALTER TABLE price_details ADD PRIMARY KEY (PRICEID);

ALTER TABLE product_details ADD PRIMARY KEY (PRODUCTID);

-- ADD FOREIGN KEY TO TABLES

ALTER TABLE order_details ADD FOREIGN KEY (PRODUCTID) REFERENCES product_details(PRODUCTID);

ALTER TABLE order_details ADD FOREIGN KEY (PRICEID) REFERENCES price_details(PRICEID);

-- RETERIVE DATA FROM order_details AND price_details

SELECT O.ORDERID, O.ORDERQUANTITY, P.PRICE as PRICE_EACH, O.TOTALPRICE 
FROM order_details O INNER JOIN price_details P 
ON O.PRICEID=P.PRICEID;

-- RETERIVE DATA FROM order_details , price_details AND product_details

SELECT O.ORDERID, P.PRODUCTNAME ,O.ORDERQUANTITY, O.TOTALPRICE
FROM order_details O INNER JOIN product_details P
ON O.PRODUCTID=P.PRODUCTID;

-- RETERIVE DATA FROM order_details AND product_details


SELECT ORD.ORDERID, PRO.PRODUCTNAME, ORD.ORDERQUANTITY, PRI.PRICE as PRICE_EACH, ORD.TOTALPRICE 
FROM order_details ORD INNER JOIN price_details PRI 
ON ORD.PRICEID=PRI.PRICEID INNER JOIN product_details PRO 
ON ORD.PRODUCTID=PRO.PRODUCTID;

-- RETERIVE ALL DATA FROM TABLES

SELECT * FROM customer_details;
SELECT * FROM order_details;
SELECT * FROM product_details;



